#!/usr/bin/env python

import shutil
import argparse
import xml.etree.ElementTree as ET
from subprocess import call
import os
import urllib as ul

parser = argparse.ArgumentParser(description='deals with args')
parser.add_argument('-n', '--name', help='The name of the playlist to convert to oggs.', required=True)
parser.add_argument('-o', '--output_dir', default='ogg_encoded', help='the directory to put the converted files in.', required=False)
args = parser.parse_args()
playlist_name = str(args.name)

if args.output_dir == 'ogg_encoded':
    output_dir = playlist_name + '_' + args.output_dir
else:
    output_dir = args.output_dir

if not os.path.exists(output_dir):
        os.makedirs(output_dir)

homedir = os.getenv('HOME')
playlists = ET.parse(homedir + '/.local/share/rhythmbox/playlists.xml')
songs = playlists.findall(".//*[@name='{0}']/location".format(playlist_name))

for song in songs:
    absolute_path = ul.unquote_plus(song.text).replace('file://', '')
    path, filename = os.path.split(absolute_path)
    name, file_extension = os.path.splitext(filename)
    if file_extension == '.ogg':
        shutil.copy(absolute_path, output_dir)
    else:
        output_file = os.path.join(output_dir, name.replace(' ', '_') + '.ogg')
        call(["oggenc", "-q 8", '-o' + output_file, absolute_path])
